fixtures:
  forge_modules:
    stdlib              : "puppetlabs/stdlib"
    nodejs              : "puppetlabs/nodejs"
    gpg_key             : "treydock/gpg_key"
    download_uncompress : "dsestero/download_uncompress"
    apt                 : "puppetlabs/apt"
