matrix:
  fast_finish: true
  include:
  - rvm: 2.0.0
    env: PUPPET_VERSION=3.6.0
  - rvm: 2.0.0
    env: PUPPET_VERSION=3.8.7
  - rvm: 2.0.0
    env: PUPPET_VERSION=4.0
  - rvm: 2.3.1
    env: PUPPET_VERSION=4.1
  - rvm: 2.3.1
    env: PUPPET_VERSION=4.2
  - rvm: 2.3.1
    env: PUPPET_VERSION=4.3
  - rvm: 2.3.1
    env: PUPPET_VERSION=4.4
  - rvm: 2.3.1
    env: PUPPET_VERSION=4.5
  - rvm: 2.3.1
    env: PUPPET_VERSION=4.6
  - rvm: '2.1'
    sudo: required
    services: docker
    env: PUPPET_VERSION="3.8.7" BEAKER_set="centos-6-docker"
    script:
#      - rake lint
#      - rake validate
#      - rake spec 
      - rake beaker
  
  allow_failures:
    -env: PUPPET_VERSION="3.8.7" BEAKER_set="centos-6-docker"
sudo: false
script:
  - "rake lint"
  - "rake validate"
  - "rake spec SPEC_OPTS='--format documentation'"
install:
  - bundle install
  - rspec-puppet-init
