matrix:
  fast_finish: true
  include:
  - rvm: 2.0.0
    env: PUPPET_VERSION=3.5.0
  - rvm: 2.0.0
    env: PUPPET_VERSION=3.8.7
  - rvm: 2.0.0
    env: PUPPET_VERSION=4.4
sudo: false
script:
  - "rake spec SPEC_OPTS='--format documentation'"
install:
  - bundle install
  - rspec-puppet-init
