matrix:
  fast_finish: true
  include:
  - rvm: 2.0.0
    env: PUPPET_VERSION=3.8.7
#  - rvm: 2.3.1 # works locally so needs more infestigation on why travis fails.
#    env: PUPPET_VERSION=4.5.2
  - rvm: '2.0.0'
    sudo: required
    services: docker
    env: PUPPET_VERSION="3.8.7" BEAKER_set="centos-6-docker"
    script:
      - rake beaker
  - rvm: 2.3.1
    sudo: required
    services: docker
    env: PUPPET_INSTALL_TYPE=agent PUPPET_INSTALL_VERSION=1.6.1 BEAKER_set="centos-6-docker"
    script:
      - rake beaker
  - rvm: 2.3.1
    sudo: required
    services: docker
    env: PUPPET_INSTALL_TYPE=agent PUPPET_INSTALL_VERSION=1.6.1 BEAKER_set="centos-7-docker"
    script:
      - rake beaker
  allow_failures:
    -env: PUPPET_VERSION="3.8.7" BEAKER_set="centos-6-docker"
sudo: false
script:
  - "rake lint"
  - "rake validate"
  - "rake spec SPEC_OPTS='--format documentation'"
install:
  - bundle install
  - rspec-puppet-init
cache: bundler
