HOSTS:
  centos-66-x64:
    roles:
      -default
      - agent
    platform: el-6-x86_64
    box: puppetlabs/centos-6.6-64-nocm
    hypervisor: vagrant
#  ubuntu-1604-x64:
#    platform: ubuntu-1604-amd64
#    box: puppetlabs/ubuntu-16.04-64-nocm
#    hypervisor: vagrant
#  debian-82-x64:
#    roles:
#      - agent
#    platform: debian-8-amd64
#    box: puppetlabs/debian-8.2-64-nocm
#    hypervisor: vagrant
CONFIG:
  type: foss
